version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
artifacts:
  files:
    - target/spring-petclinic-1.5.1.jar
    - spring-petclinic/src/test/jmeter/petclinic_test_plan.jmx
